# -*- coding: utf-8 -*-
"""IDS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nM2lWPNiQHl5BvVeIed_LytPcV6b-LqK
"""

import time
import joblib
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from datetime import datetime

# ============================
# CONFIGURATION
# ============================
MODEL_PATH = "random_forest_model.joblib"
TARGET_ENCODER_PATH = "target_encoder.joblib"
TRAINING_COLUMNS_PATH = "training_columns.joblib"
INPUT_FILE = "/content/packet_features_with_ids (1).csv"          # tshark output file
LOG_FILE = "detections.log"
THRESHOLD = 0.5  # (not used, since model.predict() returns class directly)

# ============================
# LOAD MODEL AND ARTIFACTS
# ============================
print("[+] Loading model and encoders...")

try:
    model = joblib.load(MODEL_PATH)
    target_encoder = joblib.load(TARGET_ENCODER_PATH)
    training_columns = joblib.load(TRAINING_COLUMNS_PATH)
    print("[+] Model, encoder, and training columns loaded successfully.")
except FileNotFoundError as e:
    print(f"[!] Missing required file: {e}")
    exit(1)

# ============================
# LIVE MONITOR FUNCTION
# ============================
def follow_file(filename):
    """Continuously read new lines appended to file (like tail -f)."""
    with open(filename, "r") as f:
        header_line = f.readline().strip()
        headers = header_line.split(",")
        print(f"[+] Monitoring {filename} for new packets...")
        while True:
            line = f.readline()
            if not line:
                time.sleep(1)
                continue
            yield headers, line.strip().split(",")

def monitor_live_packets():
    global training_columns

    log = open(LOG_FILE, "a", buffering=1)
    packet_count, malicious_count = 0, 0

    for headers, values in follow_file(INPUT_FILE):
        try:
            packet_count += 1
            if len(values) != len(headers):
                continue

            # --- Create DataFrame for new packet ---
            df_new = pd.DataFrame([values], columns=headers)
                        # --- Clean column names and drop duplicates ---
            df_new = df_new.loc[:, df_new.columns.notna()]
            df_new = df_new[[c for c in df_new.columns if str(c).strip() != ""]]
            df_new.columns = [str(c).strip() for c in df_new.columns]
            df_new = df_new.loc[:, ~df_new.columns.duplicated()].copy()
            training_columns = list(dict.fromkeys(training_columns))


            # Drop identifiers and IPs (same as during training)
            drop_cols = [c for c in df_new.columns if any(x in c.lower() for x in [
                "frame.number", "frame.time_epoch", "frame.time_relative",
                "tcp.stream", "udp.stream", "tcp.srcport", "tcp.dstport",
                "ip.src", "ip.dst", "unnamed", "tcp.urgent_pointer"
            ])]
            df_new = df_new.drop(columns=drop_cols, errors="ignore")

            # Replace NaN with 0
            df_new = df_new.fillna(0)

            # Encode any categorical features
            # Encode any categorical features safely
            non_numeric_cols = df_new.select_dtypes(include=["object"]).columns.tolist()
            le = LabelEncoder()

            for col in non_numeric_cols:
                try:
                    # Convert everything to string (force scalar)
                    df_new[col] = df_new[col].astype(str).apply(lambda x: x.strip())
                    # Handle single-value columns safely
                    if df_new[col].nunique() > 1:
                        df_new[col] = le.fit_transform(df_new[col])
                    else:
                        # Only one value — encoding unnecessary
                        df_new[col] = 0
                except Exception as e:
                    print(f"Error encoding column '{col}': {e}")
                    df_new[col] = 0


            print(f"Total columns in df_new before reindex: {len(df_new.columns)}")
            print(f"Unique columns in df_new: {len(set(df_new.columns))}")





            # Align with training columns
            X_new = df_new.reindex(columns=training_columns, fill_value=0)

            # --- Predict (direct classification, no probability) ---
            pred_encoded = model.predict(X_new)[0]
            pred_label = target_encoder.inverse_transform([pred_encoded])[0]

            # --- Log if malicious ---
            if pred_label.lower() == "malicious":
                malicious_count += 1
                alert = f"[{datetime.now().strftime('%H:%M:%S')}] ALERT: Malicious packet detected! (#{packet_count}, total alerts: {malicious_count})"
                print(alert)
                log.write(alert + "\n")

            # Optional: show running stats
            if packet_count % 50 == 0:
                print(f"Packets processed: {packet_count}, Alerts: {malicious_count}")

        except Exception as e:
            print(f"[!] Error processing packet: {e}")

    log.close()



# ============================
# MAIN ENTRY
# ============================
if __name__ == "__main__":
    try:
        monitor_live_packets()
    except KeyboardInterrupt:
        print("\n[+] IDS stopped by user.")