# -*- coding: utf-8 -*-
"""NetworkForest_RandomForest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cE2CDKgd0XYpo3VNk4z8w_kn89Qvb09q
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
import joblib
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, f1_score

print("--- Loading Data ---")
df = pd.read_csv('packet_features_with_ids (1).csv')
original_shape = df.shape
print(f"Original Dataset Shape: {original_shape}")

# Labeling based on IOC IP before we potentially drop it
malicious_ip = '193.160.32.4'
df['label'] = np.where((df['ip.src'] == malicious_ip) | (df['ip.dst'] == malicious_ip), 'malicious', 'benign')

# =========================================
# 2. Filtering and Justified Elimination
# =========================================
print("\n--- Phase 2: Filtering & Justification ---")

columns_to_drop = []
drop_reasons = {}

# 1. Drop Capture-Specific Identifiers (Domain Knowledge)
# frame.number is an index, time_epoch/relative binds model to specific time of capture.
identifiers = ['frame.number', 'frame.time_epoch', 'frame.time_relative', 'tcp.stream', 'udp.stream','tcp.srcport','tcp.dstport']
for col in identifiers:
    if col in df.columns:
        columns_to_drop.append(col)
        drop_reasons[col] = "Capture-specific identifier or timestamp (prevents generalization)."

# 2. Drop IPs after labeling (Domain Knowledge)
# We want the model to learn typical MALICIOUS PACKET STRUCTURES, not just "IP X is bad".
ip_cols = ['ip.src', 'ip.dst']
for col in ip_cols:
    if col in df.columns:
        columns_to_drop.append(col)
        drop_reasons[col] = "Source/Dest IP specific to this lab environment (prevents generalization)."

# 3. Drop Zero Variance Columns (Statistical)
# ip.flags.rb is almost always 0 in legitimate traffic.
if 'ip.flags.rb' in df.columns and df['ip.flags.rb'].nunique() <= 1:
    columns_to_drop.append('ip.flags.rb')
    drop_reasons['ip.flags.rb'] = "Zero variance (constant value)."

# tcp.urgent_pointer is rarely used.
if 'tcp.urgent_pointer' in df.columns and df['tcp.urgent_pointer'].nunique() <= 1:
    columns_to_drop.append('tcp.urgent_pointer')
    drop_reasons['tcp.urgent_pointer'] = "Zero variance (constant value)."

# 4. Drop "Unnamed" columns
unnamed_cols = [col for col in df.columns if 'Unnamed' in col]
for col in unnamed_cols:
    columns_to_drop.append(col)
    drop_reasons[col] = "Column with 'Unnamed' in name (likely artifact or empty)."


# Apply drops
df_filtered = df.drop(columns=columns_to_drop, errors='ignore')

print("Dropped Columns Justification:")
for col, reason in drop_reasons.items():
    print(f" - {col}: {reason}")

# =========================================
# 3. Retained Feature Handling & Encoding
# =========================================
print("\n--- Phase 3: Handling Retained Features ---")
# Remaining missing values are likely protocol specific (e.g., TCP fields are NaN in UDP packets).
# Filling with 0 is standard for 'feature not present in this packet type'.
df_filtered = df_filtered.fillna(0)

# Identify remaining non-numeric columns for encoding
non_numeric_cols = df_filtered.select_dtypes(include=['object']).columns.tolist()
# remove label from this list if present
if 'label' in non_numeric_cols: non_numeric_cols.remove('label')

print(f"Retained Categorical Features to Encode: {non_numeric_cols}")

# Label Encoding for categorical features
le = LabelEncoder()
for col in non_numeric_cols:
    # Convert to string first to handle mixed types if any slipped through
    df_filtered[col] = le.fit_transform(df_filtered[col].astype(str))

# Final Label Encoding for the target
target_le = LabelEncoder() # Use a separate encoder for the target
df_filtered['label'] = target_le.fit_transform(df_filtered['label'])

# Save the target encoder
joblib.dump(target_le, 'target_encoder.joblib')

# =========================================
# 4. Final Ready Dataset
# =========================================
print("\n--- Final Dataset Status ---")
print(f"Features Retained: {df_filtered.shape[1] - 1}")
print(f"Final Columns: {df_filtered.columns.tolist()}")

# Prepare X and y for the next phase (Training)
X = df_filtered.drop('label', axis=1)
y= df_filtered['label']

# =========================================
# 2. Time-Based Split (Preserving Order)
# =========================================
print("\n--- Performing Time-Based Split (80/20) ---")
# Assuming data is already correctly ordered by time from capture
split_idx = int(len(df) * 0.8)

X_train = X.iloc[:split_idx]
X_test = X.iloc[split_idx:]
y_train = y.iloc[:split_idx]
y_test = y.iloc[split_idx:]

print(f"Training set shape: {X_train.shape}")
print(f"Testing set shape: {X_test.shape}")
print(f"Malicious samples in train: {y_train.sum()}")
print(f"Malicious samples in test: {y_test.sum()}")

# Check if split resulted in 0 malicious samples in either set
if y_train.sum() == 0 or y_test.sum() == 0:
    print("\nWARNING: Time-based split resulted in one set having ZERO malicious samples.")
    print("Model cannot be trained or tested correctly this way. Consider stratified split if order is not critical.")

y_train.head

# =========================================
# 3. Random Forest Training (Weighted)
# =========================================
print("\n--- Training Random Forest with Class Weighting ---")
rf_clf = RandomForestClassifier(
    n_estimators=200,
    class_weight='balanced',
    random_state=42,
    n_jobs=-1,
    verbose=1
)

print("Fitting model...")
rf_clf.fit(X_train, y_train)

# =========================================
# 4. Evaluation
# =========================================
print("\n--- Evaluation ---")
y_pred = rf_clf.predict(X_test)

print("\nAccuracy:", accuracy_score(y_test, y_pred))
# macro F1 is better for imbalanced data to see performance on minority class
print("F1 Score (Macro):", f1_score(y_test, y_pred, average='macro'))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

# Feature Importance Analysis
print("\nTop 10 Most Important Features:")
importances = rf_clf.feature_importances_
indices = np.argsort(importances)[::-1]
for i in range(10):
    # Ensure we don't go out of bounds if fewer than 10 features
    if i < len(indices):
        print(f"{i+1}. {X.columns[indices[i]]}: {importances[indices[i]]:.4f}")